# Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing the dataset

In [2]:
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('neo.csv')
df = df.drop(['orbiting_body', 'id', 'name', 'sentry_object'], 1)
le = LabelEncoder()
# df['sentry_object'] = le.fit_transform(df['sentry_object'])
df['hazardous'] = le.fit_transform(df['hazardous'])
# X = df.iloc[:,]
df.head()


C:\Users\rohit\AppData\Local\Temp\ipykernel_8056\173524421.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(['orbiting_body', 'id', 'name', 'sentry_object'], 1)


est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
0          1.198271          2.679415       13569.249224   5.483974e+07   
1          0.265800          0.594347       73588.726663   6.143813e+07   
2          0.722030          1.614507      114258.692129   4.979872e+07   
3          0.096506          0.215794       24764.303138   2.543497e+07   
4          0.255009          0.570217       42737.733765   4.627557e+07   

   absolute_magnitude  hazardous  
0               16.73          0  
1               20.00          1  
2               17.83          0  
3               22.20          0  
4               20.09          1

## Prep the data

In [3]:
X = df.iloc[:,:-1]
print(X)

       est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
0              1.198271          2.679415       13569.249224   5.483974e+07   
1              0.265800          0.594347       73588.726663   6.143813e+07   
2              0.722030          1.614507      114258.692129   4.979872e+07   
3              0.096506          0.215794       24764.303138   2.543497e+07   
4              0.255009          0.570217       42737.733765   4.627557e+07   
...                 ...               ...                ...            ...   
90831          0.026580          0.059435       52078.886692   1.230039e+07   
90832          0.016771          0.037501       46114.605073   5.432121e+07   
90833          0.031956          0.071456        7566.807732   2.840077e+07   
90834          0.007321          0.016370       69199.154484   6.869206e+07   
90835          0.039862          0.089133       27024.455553   5.977213e+07   

       absolute_magnitude  
0                   16.

In [4]:
y = df.iloc[:,-1]
print(y)

0        0
1        1
2        0
3        0
4        1
        ..
90831    0
90832    0
90833    0
90834    0
90835    0
Name: hazardous, Length: 90836, dtype: int64


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 12)

In [6]:
print(X_train[:15])
print(X_test[:15])
print(y_train[:15])
print(y_test[:15])

       est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
83320          0.018991          0.042466       36395.094301   2.039977e+06   
59777          0.019256          0.043057       50307.702919   5.327216e+07   
27760          0.012149          0.027167       23145.966487   1.546155e+07   
70224          0.004252          0.009507       19910.335193   3.209515e+07   
74057          0.020163          0.045086       29312.058841   6.009054e+06   
44253          0.005815          0.013003       37183.729595   3.856950e+05   
75450          0.366906          0.820427       71415.744674   4.095619e+07   
10137          0.016016          0.035813       66922.826527   6.684031e+07   
42170          0.015295          0.034201       47771.244079   3.956645e+07   
15829          0.022108          0.049436       47652.737645   7.483872e+06   
29507          0.105817          0.236614       69610.754479   5.717618e+07   
83165          0.231502          0.517654       9004

# Feature scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
print(X_train[:10])
print(X_test[:10])

[[-0.34222106 -0.34222106 -0.46142022 -1.56710517  0.75922628]
 [-0.34138979 -0.34138979  0.08850763  0.72532508  0.74887065]
 [-0.36374848 -0.36374848 -0.98512248 -0.96654484  1.0940582 ]
 [-0.38859811 -0.38859811 -1.11301825 -0.22225938  1.88108582]
 [-0.33853448 -0.33853448 -0.74139349 -1.38950524  0.71435189]
 [-0.38367888 -0.38367888 -0.4302476  -1.64112751  1.64635828]
 [ 0.75246062  0.75246062  0.92285154  0.17423576 -1.46032968]
 [-0.35158249 -0.35158249  0.74525861  1.33244437  0.88694567]
 [-0.35385055 -0.35385055 -0.01175174  0.11205101  0.92146443]
 [-0.3324138  -0.3324138  -0.01643598 -1.32351318  0.64531438]]
[[ 0.05761382  0.05761382  1.13616317 -0.66662661 -0.76995458]
 [-0.21038676 -0.21038676  0.12151961  0.56941061 -0.11409823]
 [-0.00168993 -0.00168993 -1.13610116  0.84000833 -0.66639831]
 [ 0.01717495  0.01717495 -0.37054944  0.08723965 -0.70091707]
 [-0.05653763 -0.05653763 -1.08630503  0.81001252 -0.5559383 ]
 [-0.34276889 -0.34276889  0.11420956  0.18240009  0.7

# Training the Logistic Regression model

In [9]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 10)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=10)

# Predicting the test set result

In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))
# y_pred.reshape(len(y_pred),1)
# y_test.values.reshape(len(y_test),1)

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 0]
 [0 0]]


# Making the Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[20333   180]
 [ 2021   175]]


0.9030780747721168

# Training the SVM model using rbf kernel

In [12]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel = 'rbf', random_state = 0)
classifier_svm.fit(X_train, y_train)

SVC(random_state=0)

## Predicting the Test set results

In [13]:
y_pred_svm = classifier_svm.predict(X_test)
print(np.concatenate((y_pred_svm.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)
accuracy_score(y_test, y_pred_svm)

[[20430    83]
 [ 1949   247]]


0.9105200581267339